Repository AY2425S1-CS2103-F12-3/tp, pull requests merged in 2024-11, with the labels that each got.

#165 Favourite/Un-favourite command validation
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/RatingCommand.java
  src/main/java/seedu/address/logic/commands/UnfavouriteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/restaurant/Restaurant.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedRestaurant.java
  src/test/java/seedu/address/logic/commands/FavouriteCommandTest.java
  src/test/java/seedu/address/logic/commands/UnfavouriteCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRestaurantTest.java
  src/test/java/seedu/address/testutil/RestaurantBuilder.java
  src/test/java/seedu/address/testutil/TypicalRestaurants.java
Labels: type.Bug, alpha-bug

#161 Branch dark theme
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/AB3/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.Low, severity.VeryLow

#177 Add rating to the usage guide string for AddCommand
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Bug, priority.Low, severity.Low, alpha-bug

#176 Add "Reset All Filters" button
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.Low, severity.Low, alpha-bug

#173 Refactor price feature to be decoupled from the tag system
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RatingCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/restaurant/Price.java
  src/main/java/seedu/address/model/restaurant/PriceCategory.java
  src/main/java/seedu/address/model/restaurant/PriceContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/restaurant/Restaurant.java
  src/main/java/seedu/address/model/restaurant/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedRestaurant.java
  src/main/java/seedu/address/ui/RestaurantCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditRestaurantDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FavouriteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPriceCommandTest.java
  src/test/java/seedu/address/logic/commands/UnfavouriteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/restaurant/PriceCategoryTest.java
  src/test/java/seedu/address/model/restaurant/PriceTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRestaurantTest.java
  src/test/java/seedu/address/testutil/EditRestaurantDescriptorBuilder.java
  src/test/java/seedu/address/testutil/RestaurantBuilder.java
  src/test/java/seedu/address/testutil/RestaurantUtil.java
  src/test/java/seedu/address/testutil/TypicalRestaurants.java
Labels: type.Enhancement, priority.High, severity.High

#175 Add hyperlinks/buttons for help/welcome, respectively
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/WelcomeCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/GrubTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/WelcomeCommandTest.java
Labels: type.Enhancement, priority.Low, severity.Low, alpha-bug

#184 Fix test for find command
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: priority.Low, severity.Low

#187 Add tests for find price command parser
  src/test/java/seedu/address/logic/parser/FindPriceCommandParserTest.java
Labels: type.Bug, priority.High, severity.Low, alpha-bug

#192 Add exit button in Help Window
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug, priority.Medium, severity.High, alpha-bug

#185 Fix Storage Test Cases
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateRestaurantAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidRestaurantAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalRestaurantsAddressBook.json
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: type.Task

#197 Increase test coverage for price and associated methods
  src/main/java/seedu/address/model/util/Pair.java
  src/test/java/seedu/address/logic/commands/FindPriceCommandTest.java
  src/test/java/seedu/address/model/restaurant/PriceContainsKeywordsPredicateTest.java
Labels: type.Enhancement, priority.Low, severity.Low

#200 Added HashCode Test Cases
  src/test/java/seedu/address/model/restaurant/AddressTest.java
  src/test/java/seedu/address/model/restaurant/EmailTest.java
  src/test/java/seedu/address/model/restaurant/NameTest.java
  src/test/java/seedu/address/model/restaurant/PhoneTest.java
Labels: type.Task, priority.Medium, severity.Low

#202 Add Favourite/Unfavourite Parser test
  src/test/java/seedu/address/logic/parser/FavouriteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnfavouriteCommandParserTest.java
Labels: type.Enhancement, priority.Low, severity.Low

#203 Added tests for ratings
  src/main/java/seedu/address/logic/commands/RatingCommand.java
  src/test/java/seedu/address/logic/commands/RatingCommandTest.java
  src/test/java/seedu/address/logic/parser/RatingCommandParserTest.java
Labels: type.Task

#207 Add Test Cases
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RatingCommandTest.java
  src/test/java/seedu/address/logic/parser/RatingCommandParserTest.java
  src/test/java/seedu/address/model/restaurant/RatingTest.java
Labels: type.Enhancement, priority.Medium

#198 Add support for sorting
  src/main/java/seedu/address/logic/commands/WelcomeCommand.java
  src/main/java/seedu/address/model/restaurant/UniqueRestaurantList.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/GrubTheme.css
  src/test/java/seedu/address/logic/commands/UnfavouriteCommandTest.java
Labels: type.Enhancement, priority.Low, severity.Low

#209 Relabel help window exit button to close help
  src/main/resources/view/HelpWindow.fxml
Labels: type.Enhancement, priority.Low, severity.Low, alpha-bug

#213 Update readme
  README.md
  docs/images/Ui.png
  src/main/resources/images/grubybara.png
Labels: priority.Low, severity.Low, alpha-bug, type.Doc

#214 Update Class diagrams and User guide
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/FavouriteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UnfavouriteSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/Ui.png
  docs/index.md
  src/main/java/seedu/address/model/restaurant/Restaurant.java
Labels: priority.Low, severity.Low, type.Doc

#215 Added Rating Diagram
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/RatingSequenceDiagram.puml
Labels: priority.Low, severity.Low, type.Doc

#216 Fix Missing image issue
  docs/UserGuide.md
  docs/index.md
Labels: priority.Low, severity.Low

#218 Update MainWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, priority.High, severity.Low, alpha-bug

#219 Decrease size of main window
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.Low, severity.Low, alpha-bug

#233 Fix rating issues
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/RatingCommandParser.java
  src/main/java/seedu/address/model/restaurant/Rating.java
Labels: type.Bug, severity.Low

#239 Rating message bug
  src/main/java/seedu/address/logic/Messages.java
Labels: type.Bug, priority.Low, severity.Low

#286 Fix Rating in UG
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, severity.Medium, type.Doc

#287 Fix User Guide UI
  docs/UserGuide.md
Labels: type.Bug, type.Doc

#288 Updated Diagrams
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/RatingSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Bug, type.Doc

#295 Update docs
  docs/team/weihanwong.md
Labels: type.Task, priority.Low, severity.VeryLow

#296 Update rate and edit confusion
  docs/UserGuide.md
Labels: type.Enhancement, type.Doc

#289 Fix horizontal scroll issue
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Bug, priority.Medium, severity.Medium

#294 Updated User Story
  docs/DeveloperGuide.md
Labels: type.Epic, priority.Low, severity.Low, type.Doc

#293 Add alphaneumeric check for Price
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/FindPriceCommandParser.java
Labels: type.Bug, priority.Low, severity.Low

#292 Fixed user mix up for tags price command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
  src/test/java/seedu/address/logic/parser/FindTagCommandParserTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#307 Update API links in DG
  docs/DeveloperGuide.md
Labels: priority.Low, severity.Low

#291 Fix minor documentation bugs reported in PE-D
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  src/main/java/seedu/address/model/restaurant/Name.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Bug, priority.Low, severity.Low

#318 Update UG Ui
  docs/images/Ui.png
Labels: priority.Low, severity.Low
