Repository AY2425S1-CS2103-F12-3/tp, pull requests merged in 2024-10, with the labels that each got.

#18 Add JW photo to images dir
  docs/images/sawjingwen.png
Labels: type.Task, priority.Low, severity.Low

#20 Update AboutUs
  docs/AboutUs.md
Labels: type.Task, priority.Low, severity.Low

#15 Update AboutUs
  docs/AboutUs.md
  docs/team/weihanwong.md
Labels: type.Task, priority.Low, severity.VeryLow

#12 Update AboutUs page
  docs/AboutUs.md
  docs/team/jagdeep.md
Labels: type.Task, priority.Low, severity.Low

#23 Add CI Badge
  README.md
Labels: type.Task, priority.Low, severity.Low

#26 Add Amadeus's Photo
  docs/images/amadeuseka.png
Labels: type.Task, priority.Low, severity.Low

#25 Update Site Title
  docs/_config.yml
Labels: type.Task, priority.Low, severity.Low

#14 Update Readme Ui
  docs/images/Ui.png
Labels: type.Task, priority.Low, severity.Low

#27 Add JW's page in AboutUs
  docs/AboutUs.md
  docs/team/sawjingwen.md
Labels: type.Task, priority.Low, severity.Low

#29 Update AboutUs
  docs/AboutUs.md
  docs/team/amadeus.md
Labels: type.Task, priority.Low, severity.Low

#31 Update README A4
  README.md
Labels: type.Task, priority.Low, severity.Low

#32 Update README.md
  README.md
Labels: type.Task, priority.Low, severity.Low

#34 Rename JW's AboutUs Image
  docs/AboutUs.md
  docs/images/shotnothing.png
Labels: type.Task, priority.Low, severity.Low

#37 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Bug, priority.Low, severity.Low

#42 Update Developers Guide Use Case
  docs/DeveloperGuide.md
Labels: type.Epic, priority.Low, severity.Low

#54 Fix corruption fail safe
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#56 Add Price class into data model
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Price.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Enhancement, priority.Medium, severity.VeryLow

#57 Add find tag feature
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
Labels: type.Enhancement, priority.Low, severity.Low

#48 Replace /leq with <= in developer guide
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.Low, severity.Low

#59 Update Filter Feature
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
Labels: type.Enhancement, priority.Low, severity.Low

#61 Comment test file to suppress failing CI
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
Labels: priority.Medium, severity.Low

#69 Branch update developers guide
  README.md
  docs/_config.yml
  docs/index.md
Labels: type.Enhancement, priority.High, severity.Medium

#75 Add Price Feature
  src/main/java/seedu/address/model/person/Price.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/model/person/PriceTest.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#71 Update user guide
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#81 Update user guide
  docs/UserGuide.md
Labels: type.Bug, severity.Medium

#79 Add color and ordering to price tags
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, priority.Low, severity.Low

#83 Update Help function
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Enhancement, type.Task, priority.Medium

#85 Add Favourite Command
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FavouriteCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/restaurant/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/restaurant/Restaurant.java
  src/main/java/seedu/address/model/restaurant/UniqueRestaurantList.java
  src/main/java/seedu/address/ui/RestaurantCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.Low, severity.Low

#98 Add Ratings Feature
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RatingCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RatingCommandParser.java
  src/main/java/seedu/address/model/restaurant/Rating.java
  src/main/java/seedu/address/model/restaurant/Restaurant.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedRestaurant.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/RestaurantCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditRestaurantDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRestaurantTest.java
  src/test/java/seedu/address/testutil/EditRestaurantDescriptorBuilder.java
  src/test/java/seedu/address/testutil/RestaurantBuilder.java
  src/test/java/seedu/address/testutil/TypicalRestaurants.java
Labels: type.Task, priority.High

#101 Bug fix for ratings
  src/main/java/seedu/address/logic/commands/RatingCommand.java
Labels: type.Bug, severity.High

#97 Integrate Price model and exception handling
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/restaurant/Price.java
  src/main/java/seedu/address/model/restaurant/PriceCategory.java
  src/main/java/seedu/address/model/restaurant/Restaurant.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/Pair.java
  src/test/java/seedu/address/model/restaurant/PriceTest.java
Labels: type.Enhancement, priority.High, severity.High

#105 Fix compilation issue
  src/main/java/seedu/address/model/restaurant/Restaurant.java
Labels: type.Bug, priority.High, severity.High

#103 Update Class Diagram
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task, priority.High

#106 Remove residual method introduced in merge conflict resolution
  src/main/java/seedu/address/model/restaurant/Restaurant.java
Labels: type.Bug, priority.Low, severity.High

#96 Branch filter by tag
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTagsCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/restaurant/NameContainsKeywordsPredicateTest.java
Labels: type.Task, priority.Medium, severity.Medium

#108 Add logger in EditCommandParser
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: type.Task, priority.Medium, severity.Medium

#119 Bug fix
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug, priority.High, severity.High

#114 Branch update price uml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/model/restaurant/Phone.java
  src/main/java/seedu/address/model/restaurant/Price.java
  src/main/java/seedu/address/model/restaurant/PriceCategory.java
  src/main/java/seedu/address/model/restaurant/Restaurant.java
Labels: type.Task, priority.High, severity.Low

#110 Branch update uml diagram
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/FindTagSequenceDiagram.puml
Labels: type.Enhancement, priority.Medium, severity.Medium

#121 Branch add more asserts
  src/main/java/seedu/address/model/restaurant/PriceCategory.java
  src/main/java/seedu/address/model/restaurant/Restaurant.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, priority.Low, severity.Low

#126 Redesign UI layout and theme
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/grub_logo_32.png
  src/main/resources/images/grubybara.png
  src/main/resources/view/AB3/DarkTheme.css
  src/main/resources/view/AB3/readme.md
  src/main/resources/view/Extensions.css
  src/main/resources/view/GrubTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Enhancement, priority.Low, severity.Low

#130 Fix UML diagram for Price
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Bug, priority.Medium, severity.High

#131 Add welcome command
  LICENSE
  src/main/java/seedu/address/logic/commands/WelcomeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/logic/commands/WelcomeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Enhancement, priority.Low, severity.Low

#127 Update sample data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Enhancement, priority.Low, severity.Low

#137 Update User Guide
  docs/UserGuide.md
Labels: type.Task, priority.Low, severity.Low

#149 Branch filter by tag
  src/test/java/seedu/address/logic/commands/FindTagsCommandTest.java
Labels: type.Bug, priority.Low, severity.Low, alpha-bug

#143 Update UG for favourite & unfavourite command
  docs/UserGuide.md
Labels: priority.Low, severity.Low, type.Doc

#144 Reduce font size of result box
  src/main/resources/view/GrubTheme.css
Labels: type.Bug, priority.Low, severity.Low, alpha-bug

#151 Fix inconsistent indents in welcome and help messages
  src/main/java/seedu/address/logic/commands/WelcomeCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, priority.Low, severity.Low, alpha-bug

#152 Fix logic in Sample data creation
  src/main/java/seedu/address/MainApp.java
Labels: type.Bug, priority.Medium, severity.Medium, alpha-bug

#157 Enable Assertions
  build.gradle
Labels: type.Task, priority.Medium, severity.Low
